services:
  post_db:
    image: postgres:15
    container_name: github_db
    environment:
      POSTGRES_DB: github_monitor_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d github_monitor_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: github_monitor_app
    ports:
      - "8080:8080"
    depends_on:
      post_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://post_db:5432/github_monitor_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      GITHUB_API_BASE_URL: https://api.github.com